const countries = [
    {
        country: "United States",
        hemisphere: "North",
        continent: "North America",
        capital: "Washington, D.C",
        languages: "English",
        population: 331000000,
    },
    {
        country: "Canada",
        hemisphere: "North",
        continent: "North America",
        capital: "Ottawa",
        languages: "English, French",
        population: 37600000,
    },
    {
        country: "Mexico",
        hemisphere: "North",
        continent: "North America",
        capital: "Mexico City",
        languages: "Spanish",
        population: 130000000,
    },
    {
        country: "Brazil",
        hemisphere: "South",
        continent: "South America",
        capital: "Brasília",
        languages: "Portuguese",
        population: 212000000,
    },
    {
        country: "Argentina",
        hemisphere: "South",
        continent: "South America",
        capital: "Buenos Aires",
        languages: "Spanish",
        population: 44000000,
    },
    {
        country: "Chile",
        hemisphere: "South",
        continent: "South America",
        capital: "Santiago",
        languages: "Spanish",
        population: 19000000,
    },
    {
        country: "China",
        hemisphere: "North",
        continent: "Asia",
        capital: "Beijing",
        languages: "Mandarin",
        population: 1440000000,
    },
    {
        country: "India",
        hemisphere: "North",
        continent: "Asia",
        capital: "New Delhi",
        languages: "Hindi, English",
        population: 1380000000,
    },
    {
        country: "Russia",
        hemisphere: "North",
        continent: "Europe",
        capital: "Moscow",
        languages: "Russian",
        population: 144000000,
    },
    {
        country: "Japan",
        hemisphere: "North",
        continent: "Asia",
        capital: "Tokyo",
        languages: "Japanese",
        population: 126000000,
    },
    {
        country: "Australia",
        hemisphere: "South",
        continent: "Oceania",
        capital: "Canberra",
        languages: "English",
        population: 25000000,
    },
    {
        country: "South Africa",
        hemisphere: "South",
        continent: "Africa",
        capital: "Cape Town, Bloemfontein, Pretoria",
        languages: "Zulu, Xhosa, Afrikaans, English",
        population: 58000000,
    },
];

module.exports = countries;
